// ==UserScript==
// @name         Neo Styling
// @namespace    https://pnkpxls.net/
// @version      2025-09-18
// @description  make neo pink
// @author       You
// @icon         https://i.ppxl.cc/np/pns.png
// @match        https://*.neopets.com/*
// @grant        GM.addStyle
// ==/UserScript==


GM.addStyle("#container__2020,.hp-bg-obj__2020,.hp-bg-top__2020,.hp-bg-mid__2020,.hp-bg-bottom__2020 {background:transparent!important;}");
GM.addStyle("body#neobdy,.contentModuleContent{background-color:#ffffff !important;color:#4d4d4d!important;}#nl-instream-video::before,body{color:#4dd4d4d!important;background: #ffc2db url('https://i.ppxl.cc/np/pnbgp.png')!important;}#main, .main_theme {border-left: 2px solid #fe5d9f!important;border-right: 2px solid #fe5d9f!important;}#header > table > tbody > tr:nth-child(1) > td:nth-child(1) > a > img {visibility:hidden;}#header > table > tbody > tr:nth-child(1) > td:nth-child(1) > a{display:block;height:77px;width:156px;background:url('https://i.ppxl.cc/np/gplnp.png');} .popup-header-pattern__2020, .popup-footer-pattern__2020, #ban, #header, #footer {background: #ffc2db url('https://i.ppxl.cc/np/xsnnp.png') -15px -15px round!important;background-size: 121px 58px!important;border: 0;}");
GM.addStyle(".nav-logo__2020 {background:url('https://i.ppxl.cc/np/gnnpl.png')center center no-repeat;background-size:100%;}.nav-top-pattern__2020,.footer-pattern__2020 {background:url('https://i.ppxl.cc/np/xsnnp.png') -15px round;background-size: 151px 88px;} ");
GM.addStyle(".nav-top__2020 {background: #ffc2db!important;border-bottom: 3px solid #fe5d9f!important;}");
GM.addStyle(".footer__2020 {background: #ffc2db!important;border-top: 3px solid #fe5d9f!important;}");
GM.addStyle(".nav-top-nst {background-color: #ffe7ed!important; border: 2px solid #fe5d9f!important;}");
GM.addStyle("div#content td.sidebar,.nav-profile-dropdown__2020, .news-tab-content__2020, .alerts-tab-content__2020, .tabActive__2020, .news-tab-viewall__2020, .alerts-tab-viewall__2020, #navquestsdropdown__2023 {background: #ffe7ed!important;}");
GM.addStyle("#navProfilePetExpandIcon__2020, #navnewsdropdown__2020 {background-color: #ff7fb1!important;}");
GM.addStyle(".dropdown-triangle-up__2020 {border-bottom: 13px solid #fe5d9f!important;}");
GM.addStyle("#container__2020 .games-grid h4,div.petcentral-container a,div.nf-newsfeed-container a,div.nf-spotlight-container a,.questlog-container .questlog-tabs .ql-notif, .questlog-container .questlog-groups .ql-notif,#boardList ul .pageNav .boardPageButton, #boardTopic .pageNav .boardPageButton {color: #fe5d9f!important;}");
GM.addStyle("#container__2020 .games-grid:hover h4,div.petcentral-container a:hover,div.nf-newsfeed-container a:hover,div.nf-spotlight-container a:hover,div#content td.content a:hover,div#content td.sidebar a:hover,.user.medText a:hover, ul.dropdown a:hover, #boardIndex ul li h4:hover, #boardIndex ul li p a:hover, #boardList .breadcrumbs a:hover, #boardTopic .breadcrumbs a:hover, #boardList ul li .last a:hover, #boardList ul li .last-mobile a:hover, #boardList ul li .author-mobile a:hover, #boardTopic ul li .boardPostByline a:hover, #boardTopic ul .topicNavTop .topicCreator:hover, .boardPostMessage a:hover, #boardList ul li .boardTopicTitle:hover, #boardIndex ul li .premiumBoardButton a:hover ,#boardIndex ul li .boardDesc a:hover, #boardIndex ul li h4:hover,.nav-profile-dropdown-text a:hover {color:#ff7fb1!important;}");
GM.addStyle(".nav-dropdown__2020 ul li, .nav-dropdown__2020.community-dropdown .neofriendsOnline, .nav-profile-dropdown__2020 ul li, .nav-profile-dropdown-clock__2020 { border-bottom: 2px solid #fe5d9f!important;}");
GM.addStyle(".nav-profile-dropdown__2020 .profile-dropdown-subsection { background-color: #ffc2db!important;}");
GM.addStyle(".questlog-container .questlog-body .questlog-top.tab-3 .questlog-groups .ql-group-toggle,ul.dropdown, .nav-dropdown__2020 {background-color: #ffe7ed!important; color: #4d4d4d!important; border: 2px solid #fe5d9f!important;");
GM.addStyle(".questlog-container .questlog-body .questlog-top.tab-3 .questlog-groups,.nav-dropdown__2020 ul li:hover {background:#ffc2db!important;}");
GM.addStyle(".questlog-container .questlog-top.tab-3 .questlog-groups .ql-notif,.nav-dropdown__2020.shop-dropdown .shopdropdown-tab-active { background-color: #ffe7ed!important;}");
GM.addStyle(".nav-dropdown__2020.shop-dropdown .shopdropdown-tabs {background-color: #fe5d9f!important;}");
GM.addStyle("div#content td.content a,div#content td.sidebar a,.user.medText a, #boardIndex ul li .boardDesc a,#boardIndex ul li h4,.nav-profile-dropdown-text a,div.nf-contest a,#QuestLogContent > div.questlog-tabs > div.questlog-tab,.questlog-container .questlog-body .questlog-top .questlog-groups,#boardList ul li a,.premiumBoardButton a {color:#fe5d9f!important;}");
GM.addStyle("#boardList ul .pageNav .boardPageButton-active, #boardTopic .pageNav .boardPageButton-active, #boardList ul .boardNavBottom .createTopicButton a, #boardList ul .boardNavTop .createTopicButton a {background-color: #ffe7ed!important;color: #fe5d9f!important;}");
GM.addStyle("#boardList ul .pageNav .boardPageButton:hover, #boardTopic .pageNav .boardPageButton:hover {border: 1px solid #fe5d9f!important;background-color: #ffe7ed!important;color: #fe5d9f!important;}");
GM.addStyle(".contentModuleHeaderAlt,.sidebarHeader.medText,#boardIndex h3 {color:#fe5d9f!important;background-color:#ffc2db!important;}");
GM.addStyle(".questlog-container .questlog-body .questlog-top .questlog-groups,.sidebarModule {border: 2px solid #fe5d9f!important;}");
GM.addStyle(".sidebarTable{border: 2px solid #ffe7ed!important;}");
GM.addStyle(".button-yellow__2020{background: #ffe7ed;background: -webkit-linear-gradient(#ffe7ed, #ff7fb1);background: -moz-linear-gradient(#ffe7ed,#ff7fb1);background: linear-gradient(#ffe7ed, #ff7fb1);-webkit-box-shadow: inset 0 0 0 1px rgba(255, 194, 219, 1), inset 0 -3px 2px 3px rgba(255, 127, 177, 1), inset 0 2px 0 1px rgba(255, 231, 237, 1), 0 0 0 2px rgba(0, 0, 0, 1);-moz-box-shadow: inset 0 0 0 1px rgba(255, 194, 219,1), /* Same as top of gradient */ inset 0 -3px 2px 3px rgba(255, 127, 177,1), /* Bottom Shadow */ inset 0 2px 0 1px rgba(255, 231, 237,1), /* Top Shine */ 0 0 0 2px rgba(0,0,0,1);box-shadow: inset 0 0 0 1px rgba(255, 231, 237, 1), inset 0 -3px 2px 3px rgba(255, 127, 177, 1), inset 0 2px 0 1px rgba(255, 194, 219, 1), 0 0 0 2px rgba(0, 0, 0, 1);}");
GM.addStyle(".button-yellow__2020:hover, .button-yellow__2020:focus, a:focus > .button-yellow__2020{background: #ffe7ed;background: -webkit-linear-gradient(#ff7fb1,#ffe7ed );background: -moz-linear-gradient(#ff7fb1,#ffe7ed);background: linear-gradient(#ff7fb1,#ffe7ed);-webkit-box-shadow: inset 0 0 0 1px rgba(255, 127, 177,1), /* Same as top of gradient */inset 0 -3px 2px 3px rgba(255, 127, 177,1), /* Bottom Shadow */inset 0 2px 0 1px rgba(255,255,243,1), /* Top Shine */0 0 0 2px rgba(0,0,0,1);-moz-box-shadow: inset 0 0 0 1px rgba(255, 127, 177,1), /* Same as top of gradient */inset 0 -3px 2px 3px rgba(255, 127, 177,1), /* Bottom Shadow */inset 0 2px 0 1px rgba(255,255,243,1), /* Top Shine */0 0 0 2px rgba(0,0,0,1);box-shadow: inset 0 0 0 1px rgba(255, 127, 177,1), /* Same as top of gradient */inset 0 -3px 2px 3px rgba(255, 127, 177,1), /* Bottom Shadow */inset 0 2px 0 1px rgba(255,255,243,1), /* Top Shine */0 0 0 2px rgba(0,0,0,1);}");GM.addStyle("");
GM.addStyle(".button-yellow__2020:active{background: #FE5D9F;background: -webkit-linear-gradient(#ff7fb1,#ffe7ed );background: -moz-linear-gradient(#ff7fb1,#ffe7ed);background: linear-gradient(#ff7fb1,#ffe7ed);-webkit-box-shadow: inset 0 0 0 1px rgba(255, 127, 177,1), /* Same as top of gradient */inset 0 -3px 2px 3px rgba(254, 93, 159,1), /* Bottom Shadow */inset 0 2px 0 1px rgba(255,255,243,1), /* Top Shine */0 0 0 2px rgba(0,0,0,1);-moz-box-shadow: inset 0 0 0 1px rgba(255, 127, 177,1), /* Same as top of gradient */inset 0 -3px 2px 3px rgba(254, 93, 159,1), /* Bottom Shadow */inset 0 2px 0 1px rgba(255,255,243,1), /* Top Shine */0 0 0 2px rgba(0,0,0,1);box-shadow: inset 0 0 0 1px rgba(255, 127, 177,1), /* Same as top of gradient */inset 0 -3px 2px 3px rgba(254, 93, 159,1), /* Bottom Shadow */inset 0 2px 0 1px rgba(255,255,243,1), /* Top Shine */0 0 0 2px rgba(0,0,0,1);}");
GM.addStyle(".hp-slick__2020 .slick-prev {background-image: url('https://i.ppxl.cc/np/ppcanp.png');left: 5px;}");
GM.addStyle(".hp-slick__2020 .slick-next {background-image: url('https://i.ppxl.cc/np/npcanp.png');right: 5px;}");
GM.addStyle("div#QuestLogBody.questlog-body{border:2em solid transparent;border-image:url('https://i.ppxl.cc/np/pqlnp.png') calc(100% / 3) fill / 70px 62px / 0 stretch;");
GM.addStyle(".questlog-container .ql-missed-day, .questlog-container .questlog-neopass-link,.questlog-container .questlog-timer,.questlog-container .questlog-body .questlog-top .questlog-bonus-rewards{background-color:#FFC2DB!important;}");
GM.addStyle(".questlog-container .questlog-tabs .questlog-tab.tab-3{border:transparent;border-image:url('https://i.ppxl.cc/np/pqlnptbg.png') calc(100% / 3) fill / 20px 50px / 0 stretch;");
GM.addStyle("#QuestLogContent > div.questlog-tabs > div.questlog-tab.tab-2::before,#QuestLogContent > div.questlog-tabs > div.questlog-tab.tab-3::before{border:transparent;border-image:url('https://i.ppxl.cc/np/pqlnptbg.png') calc(100% / 3) fill / 20px 50px / 0 stretch;");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");
GM.addStyle("");



